### ISSUE TITLE
What is openvpn-auth-oauth2.so used for?

### ISSUE THREAD

**Issue by ihipop** [jkroepke/openvpn-auth-oauth2#148]
### Problem Statement

There is a  openvpn-auth-oauth2.so  located in the tar ,what is this used for? I can not find any document about that

**Comment by jkroepke** [comment]
The openvpn-auth-oauth2.so implements a OpenVPN plugin interface.

Instead running openvpn-auth-oauth2 as dedicated service, it can also run as embedded plugin as part of the OpenVPN server:

> plugin /plugin/openvpn-auth-oauth2.so /plugin/config.yaml

But this is current in experimental state and I'm not sure if this should be used in production. While it works in general, I have no experience in terms of stability. From security architecture point of view, it's not a good design, since the OpenVPN server process will public available via web and the openvpn-auth-oauth2 part runs with the same permission set as the server, e.g. having access to sensitive keys.

There is a chance that it gets discontinued in the future.
