### ISSUE TITLE
Implement OR-Based Group Validation

### ISSUE THREAD

**Issue by Pionerd** [jkroepke/openvpn-auth-oauth2#155]
### Problem Statement

While testing https://github.com/jkroepke/openvpn-auth-oauth2/issues/150 I implemented group validation in my Azure setup first. I noticed that the group membership check is currently requiring a user to be a member of ALL mentioned groups (AND). I would expect (or at least would like to have the option) that a user would only need to be part of one of the mentioned groups (OR).

**Comment by jkroepke** [comment]
As I know, is can be archived by assign the mandatory groups to the Azure AD App registration itself. For example you can configure 2 group and users only need part of one group.

This is generally prefered, since users get the notice from Azure that they are not part of the group and the login would be denied.

https://learn.microsoft.com/en-us/entra/identity-platform/howto-restrict-your-app-to-a-set-of-users#assign-the-app-to-users-and-groups-to-restrict-access

**Comment by jkroepke** [comment]
But after review other solutions, the OR based approach is more commonly used then the AND based approach.
