### ISSUE TITLE
No auth after openvpn SIGHUP

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#161]
### Current Behavior

To change the openvpn's server config, the process needs to be signalled SIGHUP, which will basically restart. After that, no OAuth2 auth takes place until the openvpn-auth-oauth2 service is restarted.
Checking the management interface using telnet, I see `>HOLD:Waiting for hold release:0` after SIGHUP. I guess the auth service will release the hold only on first connect, not expecting holds later.

**Comment by jkroepke** [comment]
The `management-hold` option in OpenVPN together with systemd introduces the issue here.

In general, if the connection to the management interface terminate, openvpn-auth-oauth2 terminates, too. 

openvpn-auth-oauth2 does not support reconnecting. This is necessary, because if OpenVPN service is restarted, client id start from zero again.

If management-hold is configured, then systemd blocks the start until the state is resolved.

Since OpenVPN is a dependency of openvpn-auth-oauth2. systemd will start the openvpn-auth-oauth2 service, after the management lock is released. But the management lock will never released. Thats a deadlock.

**Comment by andreas-p** [comment]
On SIGHUP, openvpn isn't restarted, so systemd doesn't see the necessity to restart openvpn-auth-oauth2. Somehow, openvpn-auth needs to restart itself... I guess forgetting all cached tokens would be sufficient, but a complete re-init would be on the safe side.

**Comment by jkroepke** [comment]
But SIGHUP is documented as "hart restart", I would expect that the management connection will be terminated. Normally. openvpn-auth-oauth2 should also terminate here and restarted by systemd. 

Ref: https://openvpn.net/community-resources/controlling-a-running-openvpn-process/

**Comment by andreas-p** [comment]
Well that hard restart doesn't change the PID, no chance for systemd to detect.

**Comment by jkroepke** [comment]
That fine. But openvpn-auth-oauth2 should die anyways and the unit setting

https://github.com/jkroepke/openvpn-auth-oauth2/blob/ca5aefa5627bc4526fb55f290da7643c0de6b16c/packaging/openvpn-auth-oauth2.service#L21

should trigger if openvpn-auth-oauth2 dies.

What are the logs?

**Comment by andreas-p** [comment]
openvpn-auth-oauth2 doesn't die.
Zero syslog entry when SIGHUPing openvpn.

**Comment by jkroepke** [comment]
I looked into the issue and issue a `kill -HUP` does not terminate the management connection. It surprises me, that SIGHUP is documented as `hart restart` while the connection to the managed client will be alive. I could reproduce the issue and looking forward to implement a fix.

**Comment by jkroepke** [comment]
Side note:

It's not intensional that management clients are not dropped at SIGHUP, see also https://github.com/OpenVPN/openvpn/issues/499#issuecomment-1942454477
