### ISSUE TITLE
Please support/move to plugin

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#164]
### Problem Statement

Implementing the oauth2-connector as plugin is just what the plugin interface is designed for, and it has several advantages:
- common logfile
- no services dependent on each other (which causes some trouble currently)
- keeps the management interface free for managers (https://github.com/jkroepke/openvpn-auth-oauth2/issues/146)

As of 1.15.0, I wasn't able to get it working on Debian Bookworm with OpenVPN 2.6.3 (always blocking after `PLUGIN openvpn-auth-oauth2: INFO: discover oidc auto configuration with provider generic for issuer https://oidp.net`, without any network traffic to the IDP).

**Comment by jkroepke** [comment]
I'm not sure if this should be used in production. While it should works in general (last time, it works), I have no experience in terms of stability. From security architecture point of view, it's not a good design, since the OpenVPN server process will public available via web and the openvpn-auth-oauth2 part runs with the same permission set as the server, e.g. having access to sensitive keys.

Additionally, the I have zero knowledge in C code, and writing test for the plugin seems impossible. Due hard limitations in development, security flaws in the design and lack of knowledge, I have to drop the plugin at long-term.
