### ISSUE TITLE
How to log out for a while and  log in without password verification

### ISSUE THREAD

**Issue by Scumwong** [jkroepke/openvpn-auth-oauth2#248]
### Problem Statement

I have installed openvpn-auth-oauth2 and logged in with keycloak.now it works fine ,but i want to know how to configure the openvpn-auth-oauth2 and openvpn config to let me log out for a while and  log in without user and password verification

### Environment

- openvpn-auth-oauth2 Version: v1.19.1
- OpenVPN Server Version: 2.6.5
- Server OS:ubuntu
- OpenVPN Client (flavor, OS):mac openvpn connect

**Comment by jkroepke** [comment]
I guess you are looking for this: https://github.com/jkroepke/openvpn-auth-oauth2/wiki/Configuration#non-interactive-session-refresh-across-disconnects

**Comment by Scumwong** [comment]
I found this and tested ,but it does not work for me . when the network is disconnected for a while the client can connect to the openvpn without jump to the login page but when i manually disconnect and then try to connect ,it jumps to the login page and need login with username and password again.

**Comment by jkroepke** [comment]
There is no secure way to implement a remember me option at OpenVPN level, since it's impossible to store sometime like cookies at client side. 

This should be implemented at SSO side. 

For example, I have to login once into Azure AD, and then Azure AD remembers me. On new connection, the browser popups up, but I'm instantly logged-in without an additional interaction. As I know, Keycloak support something like and remember me option, too.
