### ISSUE TITLE
help with demo.

### ISSUE THREAD

**Issue by ashleyw-gh** [jkroepke/openvpn-auth-oauth2#252]
### Problem Statement

Currently, we are using OpenVPN server in tcp mode, with deferred auth and leveraging a radius connection to a backend server running NPS which is authenticating Azure logons and forcing MFA - this is working fine, and the only port we need to expose is port 443 which is the tcp listening port for openvpn. This has been working well for several years.

I'm looking into modernising the authentication and switching from radius auth to webauth using the openvpn-auth-ouath2 plugin.

I've picked up a few quirks.
- the web auth flow doesn't seem to be triggered on OpenVPN community clients 2.5.7 but does appear to be on 2.6.10. What is the minimum version of the OpenVPN community client which support oauth2?
- to be able to run up the demo in my situation, I'd like to run the demo on an Ubuntu machine and then have a separate machine as the client making the OpenVPN request so that i can better understand the flow/URLs etc.  when I configure the client ovpn file to use "remote DemoIP 1196 udp4" instead of "remote localhost 1196 udp4" and I configure the docker-compose.yml so the CONFIG_HTTP_BASEURL is set to "http://DemoIP:9000/", when the browser interaction pops up the call back address still comes back as "http://localhost:8080/realms/openvpn-auth-oauth2/protocol/......". What do I need to change to make the demo work in this topology?
- Is it possible to use this plugin in a situation where both the OpenVPN service can run on tcp port 443 as well as the call back URL for the plugin, otherwise we have to open up additional ports.

thanks.

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
Hey @ashleyw-gh 

> the web auth flow doesn't seem to be triggered on OpenVPN community clients 2.5.7 but does appear to be on 2.6.10. What is the minimum version of the OpenVPN community client which support oauth2?

In theory, version 2.5.0 or later (OpenVPN Client 2.x requires a management client to handle WebAuth, e.g. Viscosity or Tunnelblick)

See: https://github.com/jkroepke/openvpn-auth-oauth2/wiki/OpenVPN

> Is it possible to use this plugin in a situation where both the OpenVPN service can run on tcp port 443 as well as the call back URL for the plugin, otherwise we have to open up additional ports.

If you stay with 443/TCP as protocol, that should be possible by using the `port-share` option from OpenVPN. But it requires that IP validation on openvpn-auth-oauth2 side is disabled, because the client ip from openvpn-auth-oauth2 point of view would always the OpenVPN server.

> What do I need to change to make the demo work in this topology?

On the keycloak-realm.json, you have to change the values as well, for example:

https://github.com/jkroepke/openvpn-auth-oauth2/blob/6ba89ee8504f7b4c85b05e89971ff37ede2c93b4/docs/demo/keycloak-realm.json#L22
