### ISSUE TITLE
Management Interface

### ISSUE THREAD

**Issue by BourbonLiu** [jkroepke/openvpn-auth-oauth2#256]
### Problem Statement

Hello

I found openvpn-auth-oauth2 would keep connection with OpenVPN management interface.
It's say that "the OpenVPN daemon can at most support a single management client
any one time".

I wondering is there any features or configuration properties I can use, because there're  another program have to connect with OpenVPN  management interface as well.

thanks

### Environment

- openvpn-auth-oauth2 Version: 1.13.5-1
- OpenVPN Server Version: 2.6.9
- Server OS: Rocky Linux 9.3
- OpenVPN Client (flavor, OS): OpenVPN Connect

**Comment by jkroepke** [comment]
Yeah

openvpn-auth-oauth2 has the capability to expose the management inferface as well. An existing application can connect to the openvpn-auth-oauth2 interface and pass the between external application and OpenVPN. 

```
  --openvpn.pass-through.address string
    	The address of the pass-through socket. Must start with unix:// or tcp:// (env: CONFIG_OPENVPN_PASS__THROUGH_ADDRESS) (default "unix:/run/openvpn-auth-oauth2/server.sock")
  --openvpn.pass-through.enabled
    	If true, openvpn-auth-oauth2 will setup a pass-through socket for the OpenVPN management interface.  (env: CONFIG_OPENVPN_PASS__THROUGH_ENABLED)
  --openvpn.pass-through.password value
    	The password for the pass-through socket. If argument starts with file:// it reads the secret from a file. (env: CONFIG_OPENVPN_PASS__THROUGH_PASSWORD)
  --openvpn.pass-through.socket-group string
    	The group for the pass-through socket. Used only, if openvpn.pass-through.address starts with unix:// If empty, the group of the process is used. (env: CONFIG_OPENVPN_PASS__THROUGH_SOCKET__GROUP)
  --openvpn.pass-through.socket-mode uint
    	The unix file permission mode for the pass-through socket. Used only, if openvpn.pass-through.address starts with unix:// (env: CONFIG_OPENVPN_PASS__THROUGH_SOCKET__MODE) (default 660)
```

But there is no long-term experience with other real applications.

With `openvpn.pass-through.address`, all messages are passed to the connected client and back. New client messages and auth-client command are filtered out, because they will be answered by OpenVPN.

**Comment by BourbonLiu** [comment]
Hello,

First of all, thank you for your help. The pass-through socket indeed solves my problem.

But I found that after any OpenVPN client disconnect, it causes a timeout issue when I try to connection with the pass-through socket again. I am sure pass-through socket still in "LISTEN".

I'm not sure if this is an issue or it's a mistake in how I'm using it.

Thanks

**Comment by jkroepke** [comment]
Since my english skills a re a bit limited. Would it be possible to provide item list what I have extactly todo to reproduce the issue?

Like

* start openvpn server
* start openvpn-auth-oauth2
* connect to pass-through socket (how you do?)
* start openvpn client 
* do something???
* disconnect openvpn client
* do something again???

**Comment by BourbonLiu** [comment]
1. Start OpenVPN server
2. Start openvpn-auth-oauth2
3. Use socat or telnet connect to pass-through socket (connection established and enter management interface successfully)
4. Start OpenVPN client
5. Use socat or telnet connect to pass-through socket (connection established and enter management interface successfully)
6. Disconnect OpenVPN client
7. Use socat or telnet connect to pass-through socket (connection established but didn't get into management interface)
8. Restart openvpn-auth-oauth2
9. Use socat or telnet connect to pass-through socket (connection established and enter management interface successfully)

**Comment by jkroepke** [comment]
Thanks. With that, i was able to reproduce the issue and released a fix in https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.21.1

**Comment by BourbonLiu** [comment]
It works now!

Thanks!
