### ISSUE TITLE
Restrict google workspaces groups outside GCP

### ISSUE THREAD

**Issue by Laboltus** [jkroepke/openvpn-auth-oauth2#327]
### Problem Statement

I'm trying to restrict access to openvpn server for google workspaces groups according to the docs, but I get error 'admin_policy_enforced'. I checked the changelog I found out that you removed support of ServiceAccount and only use Workload Identity. My deployment is outside GCP so I believe that this is the reason. Is there a way to authenticate from outside of GCP ?

### openvpn-auth-oauth2 logs

```shell
There is no errors from openvpn-auth-oauth2, only from Google
```

### Environment

- openvpn-auth-oauth2 Version: latest
- OpenVPN Server Version: 2.6.12
- Server OS: Ubuntu 22.04
- OpenVPN Client (flavor, OS): Tunnelblick

**Comment by jkroepke** [comment]
I removed ServiceAccount authentication. As replacement, the credentials of the logged-in user are used to fetch group membership.

No Workload Identity or other special integration is used.

The API requests are on behalf of the user identity and an admin policy may block is, because of various reason. 


Maybe this helps: https://help.vanta.com/hc/en-us/articles/4408848493844-Google-Workspace-Error-400-admin-policy-enforced

**Comment by Laboltus** [comment]
Indeed, I had to add my OAuth client ID to trusted applications to get started. Thanks.
